### PR TITLE
Apollo D2 stock DM changes

### PR DESCRIPTION
**Pull request by MOARdV**
Apollo DM changes:
* change the bottom attach node to size 2, since it is about 2.5m size.
* add effects for the top-node (mission module) decoupler.
* change rcsEnabled to "True" so it's enabled by default.
* Add ModuleAblator, using stock values from the 2.5m heat shield
* Add 200 units Ablator resource.

RO MM patch changes:
* Change the section that adds ModuleAblator to a section that patches ModuleAblator so the values used for RO are the same.

I have a proposed change for the Propulsion Module as well, but I will submit that after this is closed.

### CODE REVIEW

**Comment by MOARdV** [comment]
Need to resynch to latest updates

**Comment by mcd0uble** [comment]
hey sorry I just read this, I'm pretty new to this github thing and I'm a massive noob when it comes to anything coding related. Have made quite a few changes and tried to put in some of what you suggested, although I'm not sure how to do what you mentioned about the ModuleAblator patch

**Comment by MOARdV** [comment]
Not a problem.  It takes some getting used to (I still don't know how to do some things after about 5 years using it).  It looks like you got most of my changes already, although I think my RO patch might have been too complicated.  I'll put together a new one that will hopefully also fix it so it's not applying to the stock game.

**Comment by mcd0uble** [comment]
Thanks, although I think I sorted that, it was due to using FOR instead of NEEDS which can apparently mess things up.

**Pull request closed without merging**
